serenity.console.colors = true
serenity.dry.run=false
serenity.verbose.steps=true
serenity.browser.maximized=true
webdriver.reuse.driver = false
serenity.driver.factory = net.serenitybdd.core.webdriver.driverproviders.ThreadLocalDriverProvider